### ISSUE TITLE
Mini Game - Build the Rocket (Pre-Release 1 push)

### ISSUE THREAD

**Issue by ILM126** [ILM126/AIE-Platformer#7]
The basics of this mini game will involve the player to run around the map to collect 'Scrap Metals' and 'Fuel Units' to prepare and build the rocket for lift off. The player will be given a 5 minute time limit, in which the player will try and launch as many rockets as they can!

**Tasks for Pre-Release 1**
- [x] ScrapMetal - _**Texture**_ https://github.com/ILM126/AIE-Platformer/commit/8562292df1234d29d99d9599dfd6acb7b06de829
- [x] ScrapMetal (Semi) Modular Spawning - _**Code**_ https://github.com/ILM126/AIE-Platformer/commit/729a7e5a676dc6ec4d8a92a40f56a1702e33df8e
- [x] FuelUnit - _**Texture**_ https://github.com/ILM126/AIE-Platformer/commit/b572083818645404e343a2ad49a1bb2e041106b7
- [x] FuelUnit (Semi) Modular Spawning - _**Code**_ https://github.com/ILM126/AIE-Platformer/commit/b572083818645404e343a2ad49a1bb2e041106b7
- [x] Mini Game Scene - _**Scene/Code**_ https://github.com/ILM126/AIE-Platformer/commit/216c3ad1e060b358becab83dc429c430145d7f0d
- [x] BTR Basic UI - _**Graphics/UI/Code**_ https://github.com/ILM126/AIE-Platformer/commit/a0d2820da47f5b393d9e8496f06540247ac081de
- [x] Piping Shrike Crewed Capsule - _**Texture**_ https://github.com/ILM126/AIE-Platformer/commit/da5212968956700d9dd83bcc86a23c27ba91513b
- [x] Use for Fuel Units - _**Code**_ https://github.com/ILM126/AIE-Platformer/commit/4a0610516fcabd9fda0976910841269c20b33fd8
- [x] Simple Rocket Building - _**Code**_ https://github.com/ILM126/AIE-Platformer/commit/c5c22b2f12ce751ee3e093f73341f0a4a89c99b9
- [x] Rocket Launch Sequence - _**Animation/Particles/Code**_ https://github.com/ILM126/AIE-Platformer/commit/cd07008109a0da19bf699c603bf9d008fdf924d6

**Tasks for Pre-Release 2 in new issue**
